server:
  port: 8081
  servlet:
    context-path: /jirath_blog_2

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: com.jirath.jirathblog2.pojo,com.jirath.jirathblog2.query
  mapper-locations: classpath:mybatis-mapping/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  file:
    path: /spring/log
    name: jirathBlog2.log


