spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

msg:
  success: 100
  unLogin: 201
  noPower: 202
  noAccount: 301
  passwordError: 302

  existAccount: 303
  defaultError: 700

shiro-role: user,admin,owner
shiro-salt: jirath

blog-num-every-page: 5
