spring:
  profiles:
    active: pro
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  redis:
    host: 123.57.16.225
    password: jirath
    timeout: 3000
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  cache:
    cache-names:
      - blogsys
      - blog
      - tag
      - column
      - leaveMsg
      - share
    redis:
      time-to-live: 21600000

server.tomcat.remote_ip_header: x-forwarded-for
server.tomcat.protocol_header: x-forwarded-proto
server.tomcat.port-header: X-Forwarded-Port
msg:
  success: 100
  unLogin: 201
  noPower: 202
  noAccount: 301
  passwordError: 302

  existAccount: 303
  defaultError: 700

shiro-role: user,admin,owner
shiro-salt: jirath

blog-num-every-page: 5
server:
  forward-headers-strategy: native
