spring:
  profiles:
    active: dev

msg:
  success: 100
  unLogin: 201
  noPower: 202
  noAccount: 301
  passwordError: 302
  existAccount: 303
  defaultError: 700

shiro-role: user,admin,owner
shiro-salt: jirath

blog-num-every-page: 5

management.endpoints.web.cors.allowed-origins: '*'
management.endpoints.web.cors.allowed-methods: '*'
cors:
  allowedHeader: GFkk6vdyDOE1TQJ4UKiPq9