server:
  port: 8081
  servlet:
    context-path: /jirath_blog_2

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.57.16.225:3306/jirath_blog_2?useUnicode=true&characterEncoding=utf-8
    username: jirath_blog_2
    password: jirath

cors:
  allowedHeader: GFkk6vdyDOE1TQJ4UKiPq9
  allowedOrigins: http://jirath.cn


mybatis:
  type-aliases-package: com.jirath.jirathblog2.pojo,com.jirath.jirathblog2.query
  mapper-locations: classpath:mybatis-mapping/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  file:
    path: /spring/log
    name: jirathBlog2.log

